FROM node:16-alpine as build
WORKDIR /usr/src/frontend
COPY [".", "/usr/src/frontend"]
RUN npm install
RUN npm run build

FROM nginx:alpine
WORKDIR /usr/share/nginx/html
RUN rm -rf ./*
COPY --from=build ["/usr/src/frontend/build", "."]
#COPY --from=build ["/usr/src/frontend/nginx.conf", "/etc/nginx/conf.d/default.conf" ]
ENTRYPOINT ["nginx", "-g", "daemon off;"]