FROM node:16-alpine as build
WORKDIR /usr/src/backend
COPY [".", "/usr/src/backend"]
RUN npm install
RUN npm run build


FROM node:16-alpine as final
WORKDIR /usr/src/backend
COPY --from=build ["/usr/src/backend/build", "./build"]
COPY ["package.json", "."]
COPY ["server.js", "."]
RUN npm install --only=production
EXPOSE 4000
CMD ["tail", "-f"]
#CMD ["npm", "start"]