FROM node:16-alpine

RUN mkdir -p /usr/src/backend

COPY ["package.json","package-lock.json" , "/usr/src/backend/"]

WORKDIR /usr/src/backend

RUN npm install

COPY [".", "/usr/src/backend/"]

EXPOSE 4000

CMD ["npm", "run", "dev"]